### PR TITLE
Update consensys/blockscout image

### PR DESCRIPTION
**Pull request by fox0430**

### CODE REVIEW

**Review by joshuafernandes — COMMENTED** [review]
Hello @fox0430 have you tested this new version with both besu and goquorum? We reverted 4.1.3 because of usability issues to 4.0.0 which is stable

**Comment by fox0430** [comment]
@joshuafernandes 
I have tested v4.1.5 on both besu and goquorum. it seems fine.

In v4.0.0, there is a problem that cannot get valid transactions.
Can get transactions but are forever pending.

**Comment by joshuafernandes** [comment]
Hello @fox0430 this looks good, but need the CLA to be signed before we can merge. Click on `details` in the checks above to sign the CLA and we can merge

**Comment by fox0430** [comment]
@joshuafernandes 

I signed the CLA .

**Review by joshuafernandes — APPROVED** [review]
LGTM

**Pull request merged**
