### PR TITLE
Fix error - no output when compiled contracts already exist

### PR DESCRIPTION
**Pull request by Obadah-H**
When I run "node compile.js", it doesn't execute unless there are only sol files in the contract folder (because it tries to compile non-smarcontracts). Now, it checks only smartcontracts

### CODE REVIEW

**Review by joshuafernandes — COMMENTED** [review]
LGTM, could you update the file path please to https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/common/smart_contracts/scripts/compile.js At the moment we've got the same file in a couple of places so I've fixed that in #71 so its just the one place now

**Comment by Obadah-H** [comment]
Done. Now you can see it when you click on "show all changes"

**Comment by joshuafernandes** [comment]
> Done. Now you can see it when you click on "show all changes"

Sweet! thankyou @Obadah-H , just needs to bring your branch up to master and its good to go in I think

**Review by joshuafernandes — APPROVED** [review]
LGTM

**Pull request merged**
