### PR TITLE
Add Splunk to Quorum Dev Quickstart

### PR DESCRIPTION
**Pull request by atoulme**
This PR integrates Splunk, Ethlogger and OpenTelemetry Collector to the quickstart as a separate option from ELK.

### CODE REVIEW

**Review by joshuafernandes — CHANGES_REQUESTED** [review]
Hi @atoulme, Adding this here so I dont loose it in slack. Really nice and looks great!! Really like what you did with the single env var OTEL_RESOURCE_ATTRIBUTES instead of the repetition :)
I'd like to change a couple of minor things before merging and we can work on requests/improvements in time if that works? We can work on updating the docs for the Splunk integration as well, but no reason to halt this PR :)

So requested changes:
- Can we change the password from admin/quickstart to admin/admin to keep it consistent with grafana
- Besu appears to only do prom/grafana or opentelemetry so I think it'd be worth putting the prom & grafana containers in the if/else section of the template? ie if the user picks splunk they shouldn't get prom/grafana at all.
- Also does validator1 in Besu also need the .env file added to it by any chance (the bootnode defnition)?

We're good to merge otherwise I think, fantastic work mate!

**Comment by atoulme** [comment]
Sure thing.
* [X] Can we change the password from admin/quickstart to admin/admin to keep it consistent with grafana
* [ ] Besu appears to only do prom/grafana or opentelemetry so I think it'd be worth putting the prom & grafana containers in the if/else section of the template? ie if the user picks splunk they shouldn't get prom/grafana at all.
* [ ] Also does validator1 in Besu also need the .env file added to it by any chance (the bootnode definition)?

**Comment by atoulme** [comment]
Changes applied. However, I could not comply with making the admin password "admin". It is considered too short and Splunk refuses to start if provided.

**Review by joshuafernandes — APPROVED** [review]

**Review by joshuafernandes — APPROVED** [review]
Hi @atoulme good to go mate, think it just needs to be pulled to head and can merge

**Comment by atoulme** [comment]
Updated to latest head, please merge.

**Pull request merged**
