### PR TITLE
Updated Sirato to Chainlens

### PR DESCRIPTION
**Pull request by NickSneo**
Necessary changes for updating Sirato to Chainlens

### CODE REVIEW

**Comment by NickSneo** [comment]
@macfarla Can you please review this?

**Comment by joshuafernandes** [comment]
Hi @NickSneo, looks good. Do we need to update the docs to reflect the name change too for Besu and GoQuourum?

**Comment by NickSneo** [comment]
> Hi @NickSneo, looks good. Do we need to update the docs to reflect the name change too for Besu and GoQuourum?

Hey @joshuafernandes Thanks for the review. I have already raised PRs in Besu and GoQuorum docs for the name change

**Comment by joshuafernandes** [comment]
LGTM

**Review by joshuafernandes — APPROVED** [review]
LGTM

**Pull request merged**
